### ISSUE TITLE
Integración de esquemas de datos al entorno de GitHub y tratamiento de Bases de Datos

### ISSUE THREAD

**Issue by tomcrojo** [albertoarchena/xadvisor#6]

**Comment by albertoarchena** [comment]
@tommcrojo Normalmente las bases de datos no se suelen subir a los repositorios. Se debe a que no es éticamente correcto y mucho menos seguro subir archivos de datos, ya que estos pueden ser privados o datos delicados.

Lo normal es subir los esquemas de estas. Ya que asi los desarrolladores pueden ejecutar en local, usando el esquema que se va a usar en produccion

**Comment by tomcrojo** [comment]
Okok thanks!
